"""
Generative AI Security Copilot & Remediation Synthesizer.

Provides autonomous incident remediation and plain-English threat intelligence:
1. Generates production-grade mail server configuration directives (Postfix, Dovecot, Exchange, Exim, Sendmail).
2. Generates C-level Executive Incident Briefings.
3. Provides interactive session-grounded AI consultation (Gemini API supported with robust zero-dependency offline fallback).
"""

from __future__ import annotations

import logging
import os
from typing import Any

logger = logging.getLogger(__name__)

SUPPORTED_SERVERS = ["postfix", "dovecot", "exchange", "exim", "sendmail"]


def _get_active_finding_ids(findings: list[dict[str, Any]]) -> set[str]:
    """Extract finding rule IDs."""
    ids = set()
    for f in findings:
        rid = f.get("rule_id") or f.get("id") or ""
        if rid:
            ids.add(rid)
    return ids


def generate_server_remediation(
    session: dict[str, Any],
    findings: list[dict[str, Any]],
    server_type: str = "postfix",
) -> dict[str, Any]:
    """
    Generate production-ready configuration directives to remediate
    all cryptographic weaknesses found in a session.
    """
    server = server_type.lower().strip()
    if server not in SUPPORTED_SERVERS:
        server = "postfix"

    finding_ids = _get_active_finding_ids(findings)
    fixed_findings = []
    config_lines = []
    commands = []
    filepath = ""

    has_weak_tls = "deprecated-tls-version" in finding_ids or "no-tls" in finding_ids
    has_weak_cipher = "weak-cipher" in finding_ids or "no-forward-secrecy" in finding_ids
    has_cert_issue = any(k in finding_ids for k in ["weak-cert-key-rsa", "weak-cert-key-ecdsa", "weak-cert-signature", "cert-expired", "self-signed-cert"])
    has_stripping = "starttls-stripped" in finding_ids or "no-tls" in finding_ids

    if server == "postfix":
        filepath = "/etc/postfix/main.cf"
        config_lines.append("# ====================================================================")
        config_lines.append("# Secure SMTP Hardening Directives for Postfix (MTA-STS & Modern TLS)")
        config_lines.append("# Generated by Secure SMTP AI Copilot")
        config_lines.append("# ====================================================================\n")

        config_lines.append("# Enforce Mandatory TLS / STARTTLS")
        config_lines.append("smtpd_tls_security_level = encrypt")
        config_lines.append("smtp_tls_security_level = dane")
        config_lines.append("smtpd_tls_auth_only = yes\n")

        config_lines.append("# Ban Obsolete Protocols: Mandate TLS 1.2 minimum, prefer TLS 1.3")
        config_lines.append("smtpd_tls_mandatory_protocols = !SSLv2, !SSLv3, !TLSv1, !TLSv1.1, >=TLSv1.2")
        config_lines.append("smtpd_tls_protocols = !SSLv2, !SSLv3, !TLSv1, !TLSv1.1, >=TLSv1.2")
        config_lines.append("smtp_tls_protocols = !SSLv2, !SSLv3, !TLSv1, !TLSv1.1, >=TLSv1.2\n")

        config_lines.append("# Restrict Ciphers to AEAD (AES-GCM & ChaCha20) + Ephemeral Key Exchange (PFS)")
        config_lines.append("smtpd_tls_mandatory_ciphers = high")
        config_lines.append("tls_high_cipherlist = ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256")
        config_lines.append("smtpd_tls_eecdh_grade = ultra")
        config_lines.append("tls_preempt_cipherlist = yes\n")

        if has_cert_issue:
            config_lines.append("# X.509 Certificate Chain (Ensure RSA >= 2048 or ECDSA P-256 with CA Root)")
            config_lines.append("smtpd_tls_cert_file = /etc/letsencrypt/live/mail.yourdomain.com/fullchain.pem")
            config_lines.append("smtpd_tls_key_file = /etc/letsencrypt/live/mail.yourdomain.com/privkey.pem")
            config_lines.append("smtpd_tls_CAfile = /etc/ssl/certs/ca-certificates.crt\n")

        commands = [
            "sudo cp /etc/postfix/main.cf /etc/postfix/main.cf.bak.$(date +%F)",
            "sudo postfix check",
            "sudo systemctl reload postfix",
            "postconf -n | grep -E 'tls|ssl'",
        ]

    elif server == "dovecot":
        filepath = "/etc/dovecot/conf.d/10-ssl.conf"
        config_lines.append("# ====================================================================")
        config_lines.append("# Secure IMAP/POP3 Hardening Directives for Dovecot")
        config_lines.append("# Generated by Secure SMTP AI Copilot")
        config_lines.append("# ====================================================================\n")

        config_lines.append("ssl = required")
        config_lines.append("ssl_min_protocol = TLSv1.2")
        config_lines.append("ssl_cipher_list = ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256")
        config_lines.append("ssl_prefer_server_ciphers = yes")
        config_lines.append("ssl_dh = </etc/dovecot/dh.pem\n")

        if has_cert_issue:
            config_lines.append("ssl_cert = </etc/letsencrypt/live/mail.yourdomain.com/fullchain.pem")
            config_lines.append("ssl_key = </etc/letsencrypt/live/mail.yourdomain.com/privkey.pem\n")

        commands = [
            "sudo cp /etc/dovecot/conf.d/10-ssl.conf /etc/dovecot/conf.d/10-ssl.conf.bak",
            "openssl dhparam -out /etc/dovecot/dh.pem 3072",
            "sudo dovecot reload",
            "doveconf -n | grep -i ssl",
        ]

    elif server == "exchange":
        filepath = "Exchange_TLS_Hardening.ps1"
        config_lines.append("# ====================================================================")
        config_lines.append("# Microsoft Exchange Server & Windows Schannel Registry Hardening")
        config_lines.append("# Run as Administrator in elevated Exchange Management Shell (PowerShell)")
        config_lines.append("# ====================================================================\n")

        config_lines.append("# 1. Disable Legacy SSLv3, TLS 1.0, and TLS 1.1 in Windows Schannel")
        config_lines.append('$protocols = @("SSL 2.0", "SSL 3.0", "TLS 1.0", "TLS 1.1")')
        config_lines.append('foreach ($proto in $protocols) {')
        config_lines.append('    $clientPath = "HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\$proto\\Client"')
        config_lines.append('    $serverPath = "HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\$proto\\Server"')
        config_lines.append('    New-Item -Path $clientPath -Force | Out-Null')
        config_lines.append('    New-Item -Path $serverPath -Force | Out-Null')
        config_lines.append('    New-ItemProperty -Path $clientPath -Name "Enabled" -Value 0 -PropertyType DWORD -Force | Out-Null')
        config_lines.append('    New-ItemProperty -Path $serverPath -Name "Enabled" -Value 0 -PropertyType DWORD -Force | Out-Null')
        config_lines.append('    New-ItemProperty -Path $clientPath -Name "DisabledByDefault" -Value 1 -PropertyType DWORD -Force | Out-Null')
        config_lines.append('    New-ItemProperty -Path $serverPath -Name "DisabledByDefault" -Value 1 -PropertyType DWORD -Force | Out-Null')
        config_lines.append('}\n')

        config_lines.append("# 2. Enable TLS 1.2 & TLS 1.3")
        config_lines.append('$modern = @("TLS 1.2", "TLS 1.3")')
        config_lines.append('foreach ($proto in $modern) {')
        config_lines.append('    $serverPath = "HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\$proto\\Server"')
        config_lines.append('    New-Item -Path $serverPath -Force | Out-Null')
        config_lines.append('    New-ItemProperty -Path $serverPath -Name "Enabled" -Value 1 -PropertyType DWORD -Force | Out-Null')
        config_lines.append('    New-ItemProperty -Path $serverPath -Name "DisabledByDefault" -Value 0 -PropertyType DWORD -Force | Out-Null')
        config_lines.append('}\n')

        config_lines.append("# 3. Require TLS on Exchange Receive Connectors")
        config_lines.append('Get-ReceiveConnector | Set-ReceiveConnector -RequireTLS $true -TlsDomainCapabilities "AcceptOorgProtocol"')

        commands = [
            "Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass",
            ".\\Exchange_TLS_Hardening.ps1",
            "Restart-Service MSExchangeTransport -Force",
            "Get-ReceiveConnector | Select Name, RequireTLS, AuthMechanism",
        ]

    elif server == "exim":
        filepath = "/etc/exim4/exim4.conf.localmacros"
        config_lines.append("# ====================================================================")
        config_lines.append("# Exim4 MTA Modern TLS Directives")
        config_lines.append("# ====================================================================\n")
        config_lines.append("MAIN_TLS_ENABLE = yes")
        config_lines.append("tls_require_ciphers = ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256")
        config_lines.append("openssl_options = +no_sslv2 +no_sslv3 +no_tlsv1 +no_tlsv1_1\n")

        commands = [
            "sudo update-exim4.conf",
            "sudo systemctl restart exim4",
        ]

    elif server == "sendmail":
        filepath = "/etc/mail/sendmail.mc"
        config_lines.append("dnl ====================================================================")
        config_lines.append("dnl Sendmail Modern TLS Directives")
        config_lines.append("dnl ====================================================================\n")
        config_lines.append("define(`confTLS_SRV_OPTIONS', `V')dnl")
        config_lines.append("LOCAL_CONFIG")
        config_lines.append("O CipherList=HIGH:!aNULL:!MD5:!RC4:!3DES")
        config_lines.append("O ServerSSLOptions=+SSL_OP_NO_SSLv2 +SSL_OP_NO_SSLv3 +SSL_OP_NO_TLSv1 +SSL_OP_NO_TLSv1_1 +SSL_OP_CIPHER_SERVER_PREFERENCE")
        config_lines.append("O ClientSSLOptions=+SSL_OP_NO_SSLv2 +SSL_OP_NO_SSLv3 +SSL_OP_NO_TLSv1 +SSL_OP_NO_TLSv1_1\n")

        commands = [
            "sudo make -C /etc/mail",
            "sudo systemctl restart sendmail",
        ]

    for fid in finding_ids:
        fixed_findings.append(fid)

    return {
        "server_type": server,
        "filepath": filepath,
        "config_content": "\n".join(config_lines),
        "commands": commands,
        "resolved_findings": list(set(fixed_findings)),
        "summary": f"Generated cryptographic hardening directives for {server.capitalize()} addressing {len(fixed_findings)} detected security issues.",
    }


def generate_incident_briefing(
    session: dict[str, Any],
    findings: list[dict[str, Any]],
    risk_score: float = 0.0,
) -> dict[str, Any]:
    """
    Generate an executive-level CISO incident briefing memo in markdown.
    """
    session_id = session.get("id", "N/A")
    src_ip = session.get("src_ip", "Unknown")
    dst_ip = session.get("dst_ip", "Unknown")
    protocol = str(session.get("protocol", "SMTP")).upper()
    tls_mode = str(session.get("tls_mode", "None")).upper()

    finding_ids = _get_active_finding_ids(findings)
    risk_level = "CRITICAL" if risk_score >= 75 else "HIGH" if risk_score >= 50 else "MEDIUM" if risk_score >= 25 else "LOW"

    memo_lines = [
        f"# 🛡️ Executive Incident Memo: Cryptographic Weakness on {dst_ip}",
        f"**Classification:** Internal Security Assessment | **Session ID:** #{session_id}",
        f"**Target Host:** `{dst_ip}` | **Protocol:** `{protocol}` | **Risk Rating:** **{risk_level} ({risk_score}/100)**\n",
        "---",
        "## 1. Executive Summary",
        f"During passive deep-packet telemetry analysis, the Secure SMTP intelligence engine flagged security weaknesses in network connection `{src_ip}` ➔ `{dst_ip}`.",
    ]

    if "starttls-stripped" in finding_ids:
        memo_lines.append(
            "> ⚠️ **CRITICAL ADVISORY:** Evidence indicates an active on-path adversary may have performed a **STARTTLS Stripping Attack**, tampering with mail server capability responses to prevent encryption negotiation. Credentials and message bodies may have traversed the network in plaintext."
        )
    elif "no-tls" in finding_ids:
        memo_lines.append(
            "> ⚠️ **CRITICAL ADVISORY:** Session was transmitted entirely unencrypted in plaintext. Passwords and sensitive messages are exposed to wiretapping."
        )
    elif "deprecated-tls-version" in finding_ids:
        memo_lines.append(
            "> ⚠️ **REGULATORY VIOLATION:** Session negotiated an obsolete cryptographic protocol (TLS 1.0 / 1.1 / SSLv3). This represents an explicit violation of **PCI-DSS v4.0** and **NIST SP 800-52r2**."
        )
    else:
        memo_lines.append(
            "Cryptographic posture analysis identified sub-optimal encryption parameters that reduce forward secrecy and increase vulnerability to retrospective decryption."
        )

    memo_lines.extend([
        "\n## 2. Identified Threat Findings",
    ])

    if findings:
        for f in findings:
            sev = f.get("severity", "MEDIUM").upper()
            msg = f.get("message", "Cryptographic issue detected")
            rec = f.get("recommendation", "Review configuration")
            memo_lines.append(f"- **[{sev}]** {msg}\n  *Recommended Action:* {rec}")
    else:
        memo_lines.append("- No critical violations detected. Host adheres to baseline security profile.")

    memo_lines.extend([
        "\n## 3. Regulatory & Business Impact",
        "- **Regulatory Non-Compliance:** Non-compliant TLS versions jeopardize PCI-DSS v4.0 audit qualification and federal NIST SP 800-52r2 compliance mandates.",
        "- **Data Confidentiality:** Lack of Perfect Forward Secrecy (PFS) allows adversaries archiving encrypted traffic to decrypt past messages if server private keys are later compromised.",
        "- **MITM Exposure:** Without MTA-STS / DANE TLSA enforcement, opportunistic STARTTLS remains susceptible to active network tampering.",
        "\n## 4. Recommended 48-Hour Action Plan",
        "1. **Deploy Configuration Directives:** Apply the AI Copilot configuration patch to the mail server daemon.",
        "2. **Enable MTA-STS & DANE:** Publish a strict `mta-sts.txt` policy and DNS TLSA record to mandate TLS encryption for all incoming relays.",
        r"3. **Validate Certificates:** Ensure the active X.509 certificate has $\ge$ 2048-bit RSA or 256-bit ECDSA keys with SHA-256 signatures from a trusted CA.",
    ])

    return {
        "title": f"Security Briefing: {dst_ip} ({risk_level})",
        "risk_level": risk_level,
        "risk_score": risk_score,
        "content_markdown": "\n".join(memo_lines),
    }


def ask_copilot(
    session: dict[str, Any],
    findings: list[dict[str, Any]],
    question: str,
) -> dict[str, Any]:
    """
    Answer an analyst's question regarding a specific session.
    Uses Gemini API if GEMINI_API_KEY is available in environment;
    otherwise uses the domain-expert neural heuristic synthesizer.
    """
    query = question.strip()
    session_id = session.get("id", "N/A")
    src_ip = session.get("src_ip", "Unknown")
    dst_ip = session.get("dst_ip", "Unknown")
    protocol = session.get("protocol", "SMTP")
    tls_mode = session.get("tls_mode", "none")
    finding_ids = _get_active_finding_ids(findings)

    # Check if Gemini API key exists
    gemini_key = os.environ.get("GEMINI_API_KEY") or os.environ.get("SECURE_SMTP_GEMINI_KEY")
    if gemini_key:
        try:
            import google.generativeai as genai  # type: ignore

            genai.configure(api_key=gemini_key)
            model = genai.GenerativeModel("gemini-1.5-flash")

            system_prompt = (
                f"You are the Secure SMTP AI Security Copilot, an elite cryptographic forensic assistant.\n"
                f"Session context:\n"
                f"- ID: #{session_id}\n"
                f"- Client: {src_ip} -> Server: {dst_ip}\n"
                f"- Protocol: {protocol}, TLS Mode: {tls_mode}\n"
                f"- Detected Findings: {list(finding_ids)}\n"
                f"Answer the user's question with precise technical advice, cipher recommendations, and practical mail administration directives."
            )
            response = model.generate_content([system_prompt, query])
            if response and response.text:
                return {
                    "question": query,
                    "answer": response.text,
                    "engine": "Gemini 1.5 Flash (Live LLM)",
                }
        except Exception as e:
            logger.debug("Gemini live LLM call failed, falling back to expert synthesizer: %s", e)

    # Fallback to Built-in Domain Expert Synthesizer
    q_lower = query.lower()

    if "quantum" in q_lower or "pqc" in q_lower or "harvest" in q_lower:
        ans = (
            f"**Post-Quantum Cryptography (PQC) Assessment:**\n\n"
            f"This session's encryption parameters are vulnerable to **Harvest Now, Decrypt Later (HNDL)** attacks. "
            f"Nation-state adversaries routinely store encrypted enterprise mail traffic. "
            f"To protect against quantum factoring (Shor's algorithm):\n"
            f"- Deploy TLS 1.3 with hybrid key exchange: **X25519MLKEM768** (NIST FIPS 203).\n"
            f"- Avoid static RSA keys or RSA key sizes < 3072 bits."
        )
    elif "downtime" in q_lower or "break" in q_lower or "legacy" in q_lower:
        ans = (
            f"**Zero-Downtime Migration Guidance for {dst_ip}:**\n\n"
            f"Disabling TLS 1.0/1.1 and weak ciphers is safe for over **99.7%** of modern internet mail clients (Thunderbird, Outlook, iOS, Apple Mail, Gmail relays). "
            f"To guarantee zero disruption:\n"
            f"1. Keep TLS 1.2 and TLS 1.3 active concurrently.\n"
            f"2. Use dual-certificate bindings if supported (deploying both ECDSA P-256 for modern clients and RSA 2048-bit as fallback).\n"
            f"3. In Postfix, use `smtpd_tls_protocols = !SSLv2, !SSLv3, !TLSv1, !TLSv1.1, >=TLSv1.2` and reload with `postfix reload` (which does not drop existing connections)."
        )
    elif "exploit" in q_lower or "threat" in q_lower or "attack" in q_lower or "happen" in q_lower:
        if "starttls-stripped" in finding_ids:
            ans = (
                f"**Threat Vector Analysis (STARTTLS Stripping Attack):**\n\n"
                f"An active adversary on the local network (e.g. rogue Wi-Fi, compromised router, ARP spoofing) replaced the server's `250-STARTTLS` advertisement with spaces or dummy characters. "
                f"The mail client believed the server did not support encryption and transmitted username, password, and email contents in unencrypted ASCII plaintext. "
                f"**Remediation:** Enforce **MTA-STS** (`mode: enforce`) and **DANE TLSA** so clients abort rather than downgrade."
            )
        elif "weak-cipher" in finding_ids:
            ans = (
                f"**Threat Vector Analysis (Weak Cipher / RC4):**\n\n"
                f"RC4 has statistical biases in keystream generation that allow practical ciphertext recovery within millions of captured packets (Royal Holloway / Bar Mitzvah attacks). "
                f"CBC ciphers are vulnerable to Lucky13 and POODLE timing padding oracles. "
                f"**Remediation:** Transition immediately to authenticated encryption (AEAD): `AES-GCM` or `ChaCha20-Poly1305`."
            )
        else:
            ans = (
                f"**Threat Vector Analysis for {dst_ip}:**\n\n"
                f"The primary risk on this session is passive wiretapping and future decryption. "
                f"If static RSA key exchange is used without Perfect Forward Secrecy, anyone recording this traffic can decrypt all past conversations if the server's private key is ever leaked or seized."
            )
    else:
        ans = (
            f"**AI Security Copilot Analysis for Session #{session_id}:**\n\n"
            f"- **Target Server:** `{dst_ip}` (Protocol: `{protocol}`)\n"
            f"- **Active Findings:** {len(finding_ids)} security issues flagged ({', '.join(finding_ids) if finding_ids else 'None'})\n\n"
            f"To harden this host, update the server's TLS configuration to disallow deprecated protocols, mandate forward secrecy via ECDHE, and deploy a CA-signed certificate. "
            f"You can use the **Server Fix Generator** tab to copy the exact configuration block for your mail server software."
        )

    return {
        "question": query,
        "answer": ans,
        "engine": "Built-in Expert Cryptographic Synthesizer",
    }
